/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.sumarnakreatip.uiiot;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int drawer_shadow=0x7f020000;
        public static final int ic_action_about=0x7f020001;
        public static final int ic_action_camera=0x7f020002;
        public static final int ic_action_cloud=0x7f020003;
        public static final int ic_action_email=0x7f020004;
        public static final int ic_action_gamepad=0x7f020005;
        public static final int ic_action_good=0x7f020006;
        public static final int ic_action_group=0x7f020007;
        public static final int ic_action_help=0x7f020008;
        public static final int ic_action_import_export=0x7f020009;
        public static final int ic_action_labels=0x7f02000a;
        public static final int ic_action_search=0x7f02000b;
        public static final int ic_action_settings=0x7f02000c;
        public static final int ic_action_video=0x7f02000d;
        public static final int ic_drawer=0x7f02000e;
        public static final int ic_launcher=0x7f02000f;
        public static final int user1=0x7f020010;
        public static final int user2=0x7f020011;
    }
    public static final class id {
        public static final int asal=0x7f06000d;
        public static final int batal=0x7f060022;
        public static final int button1=0x7f06001a;
        public static final int button2=0x7f060017;
        public static final int content_frame=0x7f06000b;
        public static final int drawer_icon=0x7f060002;
        public static final int drawer_itemName=0x7f060003;
        public static final int drawer_layout=0x7f06000a;
        public static final int drop=0x7f060023;
        public static final int frag1_icon=0x7f060004;
        public static final int frag1_text=0x7f060005;
        public static final int frag2_icon=0x7f060008;
        public static final int frag2_text=0x7f060009;
        public static final int frag3_icon=0x7f060006;
        public static final int frag3_text=0x7f060007;
        public static final int itemLayout=0x7f060001;
        public static final int j_b=0x7f060036;
        public static final int j_k=0x7f060018;
        public static final int jasal=0x7f060031;
        public static final int jid=0x7f06002f;
        public static final int jj_b=0x7f060035;
        public static final int jkapasitas=0x7f060033;
        public static final int jnama=0x7f06001d;
        public static final int jno_hp=0x7f06001e;
        public static final int jno_telp=0x7f06001f;
        public static final int jnpm=0x7f06002d;
        public static final int jrole=0x7f060039;
        public static final int jstatus=0x7f060020;
        public static final int jtujuan=0x7f060032;
        public static final int jw_b=0x7f06002c;
        public static final int k=0x7f060038;
        public static final int kapasitas=0x7f060034;
        public static final int ket=0x7f06002a;
        public static final int kuota=0x7f06000f;
        public static final int left_drawer=0x7f06000c;
        public static final int list_root=0x7f06002b;
        public static final int nama=0x7f060024;
        public static final int no_1=0x7f060010;
        public static final int no_2=0x7f060011;
        public static final int no_3=0x7f060012;
        public static final int no_4=0x7f060013;
        public static final int no_5=0x7f060014;
        public static final int no_6=0x7f060015;
        public static final int no_hp=0x7f06003b;
        public static final int no_telp=0x7f06003c;
        public static final int npm=0x7f06002e;
        public static final int password=0x7f060029;
        public static final int progress=0x7f060000;
        public static final int role=0x7f06003a;
        public static final int rowd=0x7f060021;
        public static final int rows=0x7f06001b;
        public static final int spasi=0x7f06003e;
        public static final int status=0x7f06003d;
        public static final int tabel=0x7f06001c;
        public static final int textView1=0x7f060026;
        public static final int textView2=0x7f060028;
        public static final int textView3=0x7f060025;
        public static final int timePicker1=0x7f06003f;
        public static final int tujuan=0x7f06000e;
        public static final int tv=0x7f060019;
        public static final int tv11=0x7f060037;
        public static final int user_id=0x7f060030;
        public static final int username=0x7f060027;
        public static final int w_b=0x7f060016;
		public static final int button3 = 0;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int batas=0x7f030001;
        public static final int custom_drawer_item=0x7f030002;
        public static final int fragment_layout_one=0x7f030003;
        public static final int fragment_layout_three=0x7f030004;
        public static final int fragment_layout_two=0x7f030005;
        public static final int home=0x7f030006;
        public static final int layout_beritebengan=0x7f030007;
        public static final int layout_profil=0x7f030008;
        public static final int layout_room=0x7f030009;
        public static final int login=0x7f03000a;
        public static final int nebeng=0x7f03000b;
        public static final int tampil=0x7f03000c;
        public static final int tampilprofil=0x7f03000d;
        public static final int tampilstatus=0x7f03000e;
        public static final int tes=0x7f03000f;
        public static final int test_layout=0x7f030010;
    }
    public static final class string {
        public static final int alamat=0x7f040026;
        public static final int app_name=0x7f040000;
        public static final int back=0x7f04002b;
        public static final int batal=0x7f040028;
        public static final int casal=0x7f040014;
        public static final int ctujuan=0x7f040015;
        public static final int drawer_close=0x7f040007;
        public static final int drawer_open=0x7f040006;
        public static final int drop=0x7f040017;
        public static final int email=0x7f040020;
        public static final int hello_world=0x7f040001;
        public static final int id=0x7f040016;
        public static final int j_b=0x7f04000e;
        public static final int j_k=0x7f040011;
        public static final int jasal=0x7f04000a;
        public static final int jekel=0x7f04001f;
        public static final int jkapasitas=0x7f04000b;
        public static final int jlokasi=0x7f040021;
        public static final int jnama=0x7f040008;
        public static final int jstatus=0x7f040025;
        public static final int jtelp=0x7f040022;
        public static final int jtujuan=0x7f040009;
        public static final int login=0x7f040005;
        public static final int nebeng=0x7f040027;
        public static final int no_1=0x7f040018;
        public static final int no_2=0x7f040019;
        public static final int no_3=0x7f04001a;
        public static final int no_4=0x7f04001b;
        public static final int no_5=0x7f04001c;
        public static final int no_6=0x7f04001d;
        public static final int no_hp=0x7f040023;
        public static final int no_hp1=0x7f040029;
        public static final int no_telp=0x7f040024;
        public static final int no_telp1=0x7f04002a;
        public static final int npm=0x7f04000c;
        public static final int pass=0x7f040003;
        public static final int role=0x7f040010;
        public static final int setting=0x7f040013;
        public static final int sid=0x7f04000f;
        public static final int signin=0x7f040004;
        public static final int spasi=0x7f04002d;
        public static final int status=0x7f04002c;
        public static final int submit=0x7f04001e;
        public static final int user=0x7f040002;
        public static final int w_b=0x7f04000d;
        public static final int w_s=0x7f040012;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f050000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f050001;
    }
}
